POST  http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "Kamal@gmail.com",
    "password": "kamal"
}

###
POST  http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "Kamal@gmail.com",
    "username": "kamaludeen",
    "password": "kamal"
}

###
POST http://localhost:3000/api/contact
Content-Type: application/json

{
    "firstName": "Muhammad",
    "lastName": "Sagir",
    "phoneNumber": "0907y78676",
    "email": "msagir@gmail.com"
}